blank_issues_enabled: true
contact_links:
  - name: Project Discussions
    url: https://github.com/Alwin-Saji/QR/discussions
    about: Please ask and answer general questions here instead of creating a bug report or feature request.
